spring.application.name=api
# Habilita o console do H2 para você ver os dados no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuração do banco em memória
spring.datasource.url=jdbc:h2:mem:bobtracedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
